[2024-07-11T15:25:35.501+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-11T15:25:35.531+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup.task1 manual__2024-07-11T15:25:34.794480+00:00 [queued]>
[2024-07-11T15:25:35.540+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup.task1 manual__2024-07-11T15:25:34.794480+00:00 [queued]>
[2024-07-11T15:25:35.541+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 6
[2024-07-11T15:25:35.592+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): task1> on 2024-07-11 15:25:34.794480+00:00
[2024-07-11T15:25:35.598+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dag_with_catchup', 'task1', 'manual__2024-07-11T15:25:34.794480+00:00', '--job-id', '63', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_catup.py', '--cfg-path', '/tmp/tmp1n27uh6u']
[2024-07-11T15:25:35.600+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=2638) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-11T15:25:35.601+0000] {standard_task_runner.py:91} INFO - Job 63: Subtask task1
[2024-07-11T15:25:35.601+0000] {standard_task_runner.py:63} INFO - Started process 2639 to run task
[2024-07-11T15:25:35.677+0000] {task_command.py:426} INFO - Running <TaskInstance: dag_with_catchup.task1 manual__2024-07-11T15:25:34.794480+00:00 [running]> on host 54a03ee1424c
[2024-07-11T15:25:35.811+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rayzo' AIRFLOW_CTX_DAG_ID='dag_with_catchup' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-07-11T15:25:34.794480+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-11T15:25:34.794480+00:00'
[2024-07-11T15:25:35.812+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-11T15:25:35.827+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-07-11T15:25:35.828+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo helloooooooooo world']
[2024-07-11T15:25:35.835+0000] {subprocess.py:86} INFO - Output:
[2024-07-11T15:25:35.837+0000] {subprocess.py:93} INFO - helloooooooooo world
[2024-07-11T15:25:35.837+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-07-11T15:25:35.838+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-11T15:25:35.889+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup, task_id=task1, run_id=manual__2024-07-11T15:25:34.794480+00:00, execution_date=20240711T152534, start_date=20240711T152535, end_date=20240711T152535
[2024-07-11T15:25:35.936+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-11T15:25:35.952+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-11T15:25:35.984+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
