[2024-07-11T15:48:51.399+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:48:51.401+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:48:51.408+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:48:51.406+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:48:51.501+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:48:51.462+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:48:51.512+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:48:51.763+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.382 seconds
[2024-07-11T15:49:22.127+0000] {processor.py:161} INFO - Started process (PID=207) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:49:22.128+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:49:22.129+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:49:22.129+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:49:22.152+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:49:22.146+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:49:22.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:49:22.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.081 seconds
[2024-07-11T15:49:52.953+0000] {processor.py:161} INFO - Started process (PID=243) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:49:52.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:49:52.956+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:49:52.955+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:49:52.979+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:49:52.974+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:49:52.980+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:49:53.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.126 seconds
[2024-07-11T15:50:23.743+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:50:23.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:50:23.746+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:50:23.746+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:50:23.769+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:50:23.764+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:50:23.771+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:50:23.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.116 seconds
[2024-07-11T15:50:54.761+0000] {processor.py:161} INFO - Started process (PID=315) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:50:54.762+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:50:54.764+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:50:54.764+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:50:54.787+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:50:54.782+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:50:54.788+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:50:54.833+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.077 seconds
[2024-07-11T15:51:25.688+0000] {processor.py:161} INFO - Started process (PID=351) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:51:25.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:51:25.691+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:51:25.691+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:51:25.715+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:51:25.709+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:51:25.716+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:51:25.773+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.090 seconds
[2024-07-11T15:51:56.531+0000] {processor.py:161} INFO - Started process (PID=387) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:51:56.532+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:51:56.534+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:51:56.534+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:51:56.593+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:51:56.587+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:51:56.594+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:51:56.764+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.238 seconds
[2024-07-11T15:52:27.404+0000] {processor.py:161} INFO - Started process (PID=423) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:52:27.406+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:52:27.409+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:52:27.408+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:52:27.439+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:52:27.433+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:52:27.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:52:27.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.277 seconds
[2024-07-11T15:52:58.233+0000] {processor.py:161} INFO - Started process (PID=459) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:52:58.234+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:52:58.235+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:52:58.235+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:52:58.259+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:52:58.253+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:52:58.260+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:52:58.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.097 seconds
[2024-07-11T15:53:29.300+0000] {processor.py:161} INFO - Started process (PID=495) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:53:29.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:53:29.304+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:53:29.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:53:29.325+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:53:29.319+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:53:29.326+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:53:29.366+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.072 seconds
[2024-07-11T15:54:00.185+0000] {processor.py:161} INFO - Started process (PID=531) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:54:00.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:54:00.190+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:54:00.189+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:54:00.231+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:54:00.222+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:54:00.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:54:00.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.120 seconds
[2024-07-11T15:54:31.040+0000] {processor.py:161} INFO - Started process (PID=567) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:54:31.042+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:54:31.046+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:54:31.046+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:54:31.088+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:54:31.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:54:31.090+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:54:31.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.199 seconds
[2024-07-11T15:55:01.861+0000] {processor.py:161} INFO - Started process (PID=603) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:55:01.862+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:55:01.864+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:55:01.863+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:55:01.885+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:55:01.880+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:55:01.886+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:55:01.926+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.072 seconds
[2024-07-11T15:55:31.984+0000] {processor.py:161} INFO - Started process (PID=639) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:55:31.985+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:55:31.986+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:55:31.986+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:55:32.009+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:55:32.003+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:55:32.010+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:55:32.103+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.125 seconds
[2024-07-11T15:56:03.050+0000] {processor.py:161} INFO - Started process (PID=675) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:56:03.051+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:56:03.053+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:56:03.052+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:56:03.077+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:56:03.071+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:56:03.078+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:56:03.172+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.127 seconds
[2024-07-11T15:56:33.848+0000] {processor.py:161} INFO - Started process (PID=711) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:56:33.849+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:56:33.852+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:56:33.852+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:56:33.876+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:56:33.871+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:56:33.877+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:56:33.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.124 seconds
[2024-07-11T15:57:04.033+0000] {processor.py:161} INFO - Started process (PID=747) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:57:04.035+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:57:04.036+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:57:04.036+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:57:04.058+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:57:04.052+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:57:04.058+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:57:04.151+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.123 seconds
[2024-07-11T15:58:48.706+0000] {processor.py:161} INFO - Started process (PID=165) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:58:48.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:58:48.714+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:58:48.713+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:58:48.754+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:58:48.743+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:58:48.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:58:48.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.136 seconds
[2024-07-11T15:59:19.208+0000] {processor.py:161} INFO - Started process (PID=201) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:59:19.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:59:19.212+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:59:19.212+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:59:19.245+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:59:19.238+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:59:19.246+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:59:19.334+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.136 seconds
[2024-07-11T15:59:49.576+0000] {processor.py:161} INFO - Started process (PID=237) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:59:49.577+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T15:59:49.579+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:59:49.578+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:59:49.603+0000] {logging_mixin.py:188} INFO - [2024-07-11T15:59:49.597+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T15:59:49.604+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T15:59:49.667+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.099 seconds
[2024-07-11T16:00:19.743+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:00:19.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T16:00:19.746+0000] {logging_mixin.py:188} INFO - [2024-07-11T16:00:19.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:00:19.781+0000] {logging_mixin.py:188} INFO - [2024-07-11T16:00:19.765+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T16:00:19.783+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:00:19.851+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.115 seconds
[2024-07-11T16:00:50.300+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:00:50.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T16:00:50.304+0000] {logging_mixin.py:188} INFO - [2024-07-11T16:00:50.303+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:00:50.331+0000] {logging_mixin.py:188} INFO - [2024-07-11T16:00:50.326+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T16:00:50.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:00:50.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.093 seconds
[2024-07-11T16:01:21.206+0000] {processor.py:161} INFO - Started process (PID=346) to work on /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:01:21.207+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/dag_with_postgres.py for tasks to queue
[2024-07-11T16:01:21.210+0000] {logging_mixin.py:188} INFO - [2024-07-11T16:01:21.210+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:01:21.236+0000] {logging_mixin.py:188} INFO - [2024-07-11T16:01:21.232+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/dag_with_postgres.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_with_postgres.py", line 18, in <module>
    task1=PostgresOperator(
          ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 485, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/operators/postgres.py", line 84, in __init__
    super().__init__(conn_id=postgres_conn_id, **kwargs)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 468, in apply_defaults
    raise AirflowException(f"missing keyword argument {missing_args.pop()!r}")
airflow.exceptions.AirflowException: missing keyword argument 'sql'
[2024-07-11T16:01:21.238+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_with_postgres.py
[2024-07-11T16:01:21.410+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/dag_with_postgres.py took 0.213 seconds
