[2024-07-15T16:18:05.170+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T16:18:05.324+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Postgres_dag.delete_data_from_table manual__2024-07-15T16:17:25.050838+00:00 [queued]>
[2024-07-15T16:18:05.353+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Postgres_dag.delete_data_from_table manual__2024-07-15T16:17:25.050838+00:00 [queued]>
[2024-07-15T16:18:05.354+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 7
[2024-07-15T16:18:05.455+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): delete_data_from_table> on 2024-07-15 16:17:25.050838+00:00
[2024-07-15T16:18:05.465+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=1550) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-07-15T16:18:05.465+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'Postgres_dag', 'delete_data_from_table', 'manual__2024-07-15T16:17:25.050838+00:00', '--job-id', '69', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres.py', '--cfg-path', '/tmp/tmp4rv4pdvz']
[2024-07-15T16:18:05.468+0000] {standard_task_runner.py:63} INFO - Started process 1553 to run task
[2024-07-15T16:18:05.470+0000] {standard_task_runner.py:91} INFO - Job 69: Subtask delete_data_from_table
[2024-07-15T16:18:05.810+0000] {task_command.py:426} INFO - Running <TaskInstance: Postgres_dag.delete_data_from_table manual__2024-07-15T16:17:25.050838+00:00 [running]> on host 32f997017b5a
[2024-07-15T16:18:06.506+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Rayzo' AIRFLOW_CTX_DAG_ID='Postgres_dag' AIRFLOW_CTX_TASK_ID='delete_data_from_table' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T16:17:25.050838+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T16:17:25.050838+00:00'
[2024-07-15T16:18:06.512+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T16:18:06.624+0000] {sql.py:276} INFO - Executing:  
        delete from drag_runs where dt = '2024-07-15' and dag_id = 'Postgres_dag'
        
[2024-07-15T16:18:06.651+0000] {base.py:84} INFO - Using connection ID 'Postgres_con' for task execution.
[2024-07-15T16:18:06.682+0000] {base.py:84} INFO - Using connection ID 'Postgres_con' for task execution.
[2024-07-15T16:18:06.775+0000] {sql.py:487} INFO - Running statement:  
        delete from drag_runs where dt = '2024-07-15' and dag_id = 'Postgres_dag'
        , parameters: None
[2024-07-15T16:18:06.795+0000] {sql.py:496} INFO - Rows affected: 1
[2024-07-15T16:18:06.859+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T16:18:06.920+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=Postgres_dag, task_id=delete_data_from_table, run_id=manual__2024-07-15T16:17:25.050838+00:00, execution_date=20240715T161725, start_date=20240715T161805, end_date=20240715T161806
[2024-07-15T16:18:07.068+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-07-15T16:18:07.179+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
